### PR TITLE
Fix mapping.forEach is not a function error in browsers

### PR DESCRIPTION
**Pull request by Gaurav0**

### CODE REVIEW

**Comment by Gaurav0** [comment]
mapping is an object

**Comment by rwjblue** [comment]
It should not be. It should be an array.

**Comment by Gaurav0** [comment]
ok. May be an issue with rollup-plugin-json. I see I get an object back.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-rfc176-data/blob/master/mappings.json is the source, and the root export is an array

**Comment by Gaurav0** [comment]
Yup. Closing.

**Comment by Gaurav0** [comment]
Issue was not with rollup-plugin-json, for some reason I was bringing in ember-rfc176-data v0.2.7 instead of v0.3.2

**Comment by rwjblue** [comment]
Ahh, gotcha. Glad you got to the bottom of it.

**Pull request closed without merging**
